version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn global add node-gyp && yarn install
      - run:
                    name: Install local dependencies
                    command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  install:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn start
      - run: yarn build
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}

  test-e2e:
    docker:
      - image: circleci/node:10-browsers
      - image: circleci/postgres:9.6.5
        environment:
          POSTGRES_DB: psqluer
          POSTGRES_USER: psqluer
          POSTGRES_PASSWORD: psqlpassword
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
      - run:
          command: yarn test:e2e
          environment:
            DATABASE_URL: postgres://psqluer:psqlpassword@localhost:5432/psqluer
            JWT_SECRET: aaaa
            API_PORT: 3000
            API_HOST: localhost
            API_PROTOCOL: http

workflows:
  version: 2
  build-test-and-lint2:
    jobs:
      - build
      - install:
          requires:
            - build
      - test-e2e:
          requires:
            - install
